name: Lint Code Base

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:

permissions: read-all

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_CHECKOV: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITLEAKS: false
          FILTER_REGEX_EXCLUDE: .github/.*
